### ISSUE TITLE
Getting python error with NVIDA Generate TensorRT engines

### ISSUE THREAD

**Issue by quic-nmorillo** [mlcommons/inference_results_v1.0#1]
I'm following the instructions to duplicate Nvidia inference workload posted here:  https://github.com/mlcommons/inference_results_v1.0/tree/master/closed/NVIDIA#readme

I'm encountered an error to generate the engine for TensorRT.  This is inside the container from "make prebuild" script

"make build" command ran successfully

root@5b106f712908:/work# make generate_engines RUN_ARGS="--benchmarks=bert --scenarios=Server --config_ver=default,high_accuracy" | tee generate.log
[2021-05-20 16:31:39,869 __init__.py:255 INFO] Running command: CUDA_VISIBILE_ORDER=PCI_BUS_ID nvidia-smi --query-gpu=gpu_name,pci.device_id,uuid --format=csv
[2021-05-20 16:31:39,882 main.py:701 INFO] Detected System ID: T4x1
[2021-05-20 16:31:39,908 main.py:529 INFO] Using config files: configs/bert/Server/config.json
[2021-05-20 16:31:39,908 __init__.py:341 INFO] Parsing config file configs/bert/Server/config.json ...
[2021-05-20 16:31:39,916 main.py:542 INFO] Processing config "T4x1_bert_Server"
[2021-05-20 16:31:40,012 main.py:82 INFO] Building engines for bert benchmark in Server scenario...
[2021-05-20 16:31:40,013 main.py:102 INFO] Building GPU engine for T4x1_bert_Server
[2021-05-20 16:31:44,273 bert_var_seqlen.py:63 INFO] Using workspace size: 5,368,709,120
[2021-05-20 16:32:02,717 __init__.py:255 INFO] Running command: CUDA_VISIBILE_ORDER=PCI_BUS_ID nvidia-smi --query-gpu=gpu_name,pci.device_id,uuid --format=csv
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/work/code/main.py", line 108, in handle_generate_engine
    b.build_engines()
  File "/work/code/bert/tensorrt/bert_var_seqlen.py", line 129, in build_engines
    weights_dict = get_onnx_fake_quant_weights(self.model_path)
  File "/work/code/bert/tensorrt/builder_utils.py", line 77, in get_onnx_fake_quant_weights
    model = onnx.load(path)
  File "/usr/local/lib/python3.6/dist-packages/onnx/__init__.py", line 115, in load_model
    model = load_model_from_string(s, format=format)
  File "/usr/local/lib/python3.6/dist-packages/onnx/__init__.py", line 152, in load_model_from_string
    return _deserialize(s, ModelProto())
  File "/usr/local/lib/python3.6/dist-packages/onnx/__init__.py", line 95, in _deserialize
    decoded = cast(Optional[int], proto.ParseFromString(s))
google.protobuf.message.DecodeError: Error parsing message
Traceback (most recent call last):
  File "code/main.py", line 703, in <module>
    main(main_args, system)
  File "code/main.py", line 634, in main
    launch_handle_generate_engine(*_gen_args, **_gen_kwargs)
  File "code/main.py", line 62, in launch_handle_generate_engine
    raise RuntimeError("Building engines failed!")
RuntimeError: Building engines failed!
make: *** [generate_engines] Error 1
Makefile:599: recipe for target 'generate_engines' failed

**Comment by quic-nmorillo** [comment]
Close this issue since it was determined that wrong model was downloaded.

**Comment by quic-nmorillo** [comment]
no error once correct model was passed in
