### ISSUE TITLE
How to create mlperf.conf

### ISSUE THREAD

**Issue by BlueCloudDev** [mlcommons/inference_results_v1.0#5]
Fails on running harness

Traceback (most recent call last):
  File "code/main.py", line 279, in handle_run_harness
    result = harness.run_harness()
  File "/mlperf/code/common/harness.py", line 265, in run_harness
    flag_dict)
  File "/mlperf/code/common/submission.py", line 69, in generate_measurements_entry
    generate_mlperf_conf(mlperf_conf_path)
  File "/mlperf/code/common/submission.py", line 85, in generate_mlperf_conf
    shutil.copyfile("build/inference/mlperf.conf", mlperf_conf_path)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'build/inference/mlperf.conf'
Traceback (most recent call last):
  File "code/main.py", line 703, in <module>
    main(main_args, system)
  File "code/main.py", line 649, in main
    handle_run_harness(benchmark_conf, need_gpu, need_dla, profile, power)
  File "code/main.py", line 288, in handle_run_harness
    raise RuntimeError("Run harness failed!")

Struggling to find any instructions on what this file is and where it comes from.

**Comment by TianningWang** [comment]
Did you run this command successfully:
`make build`

[https://github.com/mlcommons/inference_results_v1.0/blob/master/closed/NVIDIA/Makefile#L387](url)
command `make build` will run `clone_loadgen` first

[https://github.com/mlcommons/inference_results_v1.0/blob/master/closed/NVIDIA/Makefile#L395](url)
`clone_loadgen` will download a project from [https://github.com/mlcommons/inference.git](url) to 'build/inference'
mlperf.conf file is in the root directory of this download project
